
# to run Jekyll, type "jekyll --server"

#tips on building a live menu: http://stackoverflow.com/questions/11495381/struggling-to-find-array-in-jekyll-config-file-site-navigation



# specific Jekyll config
url: /
markdown: rdiscount
pygments: true
permalink: /:year/:month/:title.html
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "notes.txt"]

# debugging
auto: true


navigation:
 - text: Home
   url: /
 - text: Features
   url: /features.html
 - text: Blog
   url: /blog.html
 - text: Support
   url: /support.html
 - text: Download
   url: "/index.html#get-liztic"